// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djvknipgbbququxazhxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdmtuaXBnYmJxdXF1eGF6aHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzQzOTQsImV4cCI6MjA2NzYxMDM5NH0.CUTOBLh1AXau33O_-9YNyAZjMI-29YYK4ax_jSbxUzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});